In [20]:
# importing Libraries

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import classification_report
from sklearn.preprocessing import MinMaxScaler
import joblib

##### LOAD AND PREPROCESS DATA

In [21]:
# Load the dataset
df = pd.read_csv("irrigation_machine.csv")

In [22]:
# first 5 rows to be printed
df.head()

,Unnamed: 0,sensor_0,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,sensor_8,...,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,parcel_0,parcel_1,parcel_2
0,0,1.0,2.0,1.0,7.0,0.0,1.0,1.0,4.0,0.0,...,8.0,1.0,0.0,2.0,1.0,9.0,2.0,0,1,0
1,1,5.0,1.0,3.0,5.0,2.0,2.0,1.0,2.0,3.0,...,4.0,5.0,5.0,2.0,2.0,2.0,7.0,0,0,0
2,2,3.0,1.0,4.0,3.0,4.0,0.0,1.0,6.0,0.0,...,3.0,3.0,1.0,0.0,3.0,1.0,0.0,1,1,0
3,3,2.0,2.0,4.0,3.0,5.0,0.0,3.0,2.0,2.0,...,4.0,1.0,1.0,4.0,1.0,3.0,2.0,0,0,0
4,4,4.0,3.0,3.0,2.0,5.0,1.0,3.0,1.0,1.0,...,1.0,3.0,2.0,2.0,1.0,1.0,0.0,1,1,0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2000 non-null   int64
 1   sensor_0    2000 non-null   float64
 2   sensor_1    2000 non-null   float64
 3   sensor_2    2000 non-null   float64
 4   sensor_3    2000 non-null   float64
 5   sensor_4    2000 non-null   float64
 6   sensor_5    2000 non-null   float64
 7   sensor_6    2000 non-null   float64
 8   sensor_7    2000 non-null   float64
 9   sensor_8    2000 non-null   float64
 10  sensor_9    2000 non-null   float64
 11  sensor_10   2000 non-null   float64
 12  sensor_11   2000 non-null   float64
 13  sensor_12   2000 non-null   float64
 14  sensor_13   2000 non-null   float64
 15  sensor_14   2000 non-null   float64
 16  sensor_15   2000 non-null   float64
 17  sensor_16   2000 non-null   float64
 18  sensor_17   2000 non-null   float64
 19  sensor_18   2000 non-null   float64
 20  sensor_19   2000 non-null   float64
 21  parcel_0    2000 non-null   int64
 22  parcel_1    2000 non-null   int64
 23  parcel_2    2000 non-null   int64
dtypes: float64(20), int64(4)
memory usage: 375.1 KB

In [24]:
df.columns

Index(['Unnamed: 0', 'sensor_0', 'sensor_1', 'sensor_2', 'sensor_3',
       'sensor_4', 'sensor_5', 'sensor_6', 'sensor_7', 'sensor_8', 'sensor_9',
       'sensor_10', 'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14',
       'sensor_15', 'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19',
       'parcel_0', 'parcel_1', 'parcel_2'],
      dtype='object')

In [25]:
df = df.drop('Unnamed: 0', axis=1)
df.head()

,sensor_0,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,sensor_8,sensor_9,...,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,parcel_0,parcel_1,parcel_2
0,1.0,2.0,1.0,7.0,0.0,1.0,1.0,4.0,0.0,3.0,...,8.0,1.0,0.0,2.0,1.0,9.0,2.0,0,1,0
1,5.0,1.0,3.0,5.0,2.0,2.0,1.0,2.0,3.0,1.0,...,4.0,5.0,5.0,2.0,2.0,2.0,7.0,0,0,0
2,3.0,1.0,4.0,3.0,4.0,0.0,1.0,6.0,0.0,2.0,...,3.0,3.0,1.0,0.0,3.0,1.0,0.0,1,1,0
3,2.0,2.0,4.0,3.0,5.0,0.0,3.0,2.0,2.0,5.0,...,4.0,1.0,1.0,4.0,1.0,3.0,2.0,0,0,0
4,4.0,3.0,3.0,2.0,5.0,1.0,3.0,1.0,1.0,2.0,...,1.0,3.0,2.0,2.0,1.0,1.0,0.0,1,1,0

In [26]:
df.describe().T

            count    mean       std  min  25%  50%  75%   max
sensor_0   2000.0  1.4370  1.321327  0.0  0.0  1.0  2.0   8.0
sensor_1   2000.0  1.6590  1.338512  0.0  1.0  1.0  2.0   9.0
sensor_2   2000.0  2.6545  1.699286  0.0  1.0  2.0  4.0  10.0
sensor_3   2000.0  2.6745  1.855875  0.0  1.0  2.0  4.0  11.0
sensor_4   2000.0  2.8875  1.816451  0.0  2.0  3.0  4.0  12.0
sensor_5   2000.0  1.4110  1.339394  0.0  0.0  1.0  2.0   7.0
sensor_6   2000.0  3.3155  2.206444  0.0  2.0  3.0  5.0  13.0
sensor_7   2000.0  4.2015  2.280241  0.0  3.0  4.0  6.0  12.0
sensor_8   2000.0  1.2140  1.386782  0.0  0.0  1.0  2.0   8.0
sensor_9   2000.0  1.9010  1.518668  0.0  1.0  2.0  3.0   9.0
sensor_10  2000.0  3.0875  1.821127  0.0  2.0  3.0  4.0  10.0
sensor_11  2000.0  3.6085  2.058482  0.0  2.0  3.0  5.0  12.0
sensor_12  2000.0  4.3255  2.200220  0.0  3.0  4.0  6.0  15.0
sensor_13  2000.0  2.7315  1.774537  0.0  1.0  2.0  4.0  11.0
sensor_14  2000.0  3.4160  1.960578  0.0  2.0  3.0  5.0  11.0
sensor_15  2000.0  1.2065  1.258034  0.0  0.0  1.0  2.0   6.0
sensor_16  2000.0  2.3250  1.715181  0.0  1.0  2.0  3.0  10.0
sensor_17  2000.0  1.7295  1.561265  0.0  0.0  1.0  3.0  11.0
sensor_18  2000.0  2.2745  1.671690  0.0  1.0  2.0  3.0  10.0
sensor_19  2000.0  1.8135  1.469285  0.0  1.0  2.0  3.0   7.0
parcel_0   2000.0  0.6355  0.481410  0.0  0.0  1.0  1.0   1.0
parcel_1   2000.0  0.7305  0.443811  0.0  0.0  1.0  1.0   1.0
parcel_2   2000.0  0.2120  0.408827  0.0  0.0  0.0  0.0   1.0

STEP 2: DEFINE FEATURES AND LABELS

In [27]:
x = df.iloc[:, 0:20]
y = df.iloc[:, 20:]

In [28]:
x.sample(10)

,sensor_0,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,sensor_8,sensor_9,sensor_10,sensor_11,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19
31,1.0,3.0,4.0,1.0,6.0,2.0,1.0,7.0,0.0,4.0,2.0,4.0,4.0,3.0,3.0,2.0,2.0,3.0,2.0,3.0
684,3.0,1.0,1.0,2.0,1.0,0.0,2.0,5.0,0.0,3.0,0.0,4.0,2.0,2.0,2.0,0.0,4.0,2.0,2.0,2.0
423,0.0,1.0,0.0,3.0,4.0,2.0,2.0,0.0,1.0,4.0,2.0,3.0,7.0,1.0,4.0,1.0,3.0,2.0,5.0,4.0
760,0.0,0.0,4.0,1.0,3.0,3.0,4.0,3.0,2.0,3.0,2.0,2.0,6.0,1.0,1.0,1.0,1.0,1.0,3.0,3.0
1671,2.0,0.0,2.0,3.0,0.0,1.0,0.0,5.0,0.0,1.0,2.0,11.0,4.0,4.0,7.0,0.0,1.0,0.0,2.0,1.0
146,4.0,4.0,2.0,2.0,0.0,3.0,2.0,1.0,1.0,3.0,3.0,0.0,6.0,3.0,4.0,3.0,1.0,1.0,4.0,6.0
1847,2.0,7.0,0.0,2.0,1.0,0.0,1.0,1.0,0.0,5.0,1.0,2.0,0.0,2.0,1.0,4.0,1.0,2.0,1.0,5.0
1015,2.0,3.0,2.0,1.0,1.0,1.0,1.0,8.0,0.0,1.0,2.0,4.0,7.0,2.0,0.0,1.0,2.0,4.0,1.0,1.0
1622,1.0,4.0,2.0,2.0,5.0,2.0,7.0,5.0,1.0,3.0,3.0,0.0,3.0,0.0,4.0,0.0,2.0,2.0,0.0,3.0
1519,1.0,0.0,3.0,0.0,2.0,0.0,5.0,4.0,1.0,2.0,4.0,3.0,5.0,3.0,3.0,1.0,5.0,3.0,2.0,1.0

In [29]:
y.sample(10)

      parcel_0  parcel_1  parcel_2
1979         1         1         0
1185         1         1         0
920          0         0         0
1522         0         1         0
430          1         1         1
1568         0         0         0
328          1         1         1
963          1         1         1
616          1         1         1
1114         1         1         0

In [30]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 20 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   sensor_0   2000 non-null   float64
 1   sensor_1   2000 non-null   float64
 2   sensor_2   2000 non-null   float64
 3   sensor_3   2000 non-null   float64
 4   sensor_4   2000 non-null   float64
 5   sensor_5   2000 non-null   float64
 6   sensor_6   2000 non-null   float64
 7   sensor_7   2000 non-null   float64
 8   sensor_8   2000 non-null   float64
 9   sensor_9   2000 non-null   float64
 10  sensor_10  2000 non-null   float64
 11  sensor_11  2000 non-null   float64
 12  sensor_12  2000 non-null   float64
 13  sensor_13  2000 non-null   float64
 14  sensor_14  2000 non-null   float64
 15  sensor_15  2000 non-null   float64
 16  sensor_16  2000 non-null   float64
 17  sensor_17  2000 non-null   float64
 18  sensor_18  2000 non-null   float64
 19  sensor_19  2000 non-null   float64
dtypes: float64(20)
memory usage: 312.6 KB

In [31]:
y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   parcel_0  2000 non-null   int64
 1   parcel_1  2000 non-null   int64
 2   parcel_2  2000 non-null   int64
dtypes: int64(3)
memory usage: 47.0 KB

In [32]:
x

,sensor_0,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,sensor_8,sensor_9,sensor_10,sensor_11,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19
0,1.0,2.0,1.0,7.0,0.0,1.0,1.0,4.0,0.0,3.0,1.0,3.0,6.0,8.0,1.0,0.0,2.0,1.0,9.0,2.0
1,5.0,1.0,3.0,5.0,2.0,2.0,1.0,2.0,3.0,1.0,3.0,2.0,2.0,4.0,5.0,5.0,2.0,2.0,2.0,7.0
2,3.0,1.0,4.0,3.0,4.0,0.0,1.0,6.0,0.0,2.0,3.0,2.0,4.0,3.0,3.0,1.0,0.0,3.0,1.0,0.0
3,2.0,2.0,4.0,3.0,5.0,0.0,3.0,2.0,2.0,5.0,3.0,1.0,2.0,4.0,1.0,1.0,4.0,1.0,3.0,2.0
4,4.0,3.0,3.0,2.0,5.0,1.0,3.0,1.0,1.0,2.0,4.0,5.0,3.0,1.0,3.0,2.0,2.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,4.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,4.0,3.0,3.0,1.0,2.0,3.0,2.0,1.0,1.0,0.0
1996,1.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0,1.0,5.0,2.0,2.0,4.0,3.0,3.0,0.0,1.0,0.0,6.0,2.0
1997,1.0,3.0,3.0,1.0,1.0,4.0,8.0,1.0,0.0,0.0,3.0,2.0,4.0,2.0,3.0,4.0,4.0,4.0,1.0,0.0
1998,2.0,1.0,0.0,2.0,2.0,0.0,1.0,3.0,0.0,0.0,0.0,5.0,2.0,2.0,4.0,0.0,2.0,0.0,3.0,0.0
1999,0.0,1.0,4.0,1.0,2.0,2.0,6.0,8.0,5.0,1.0,2.0,4.0,3.0,2.0,1.0,1.0,0.0,5.0,2.0,1.0

In [33]:
x.shape, y.shape

((2000, 20), (2000, 3))